# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
commands:
  print-pipeline-id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  print-workflow-id:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "print workflow ID"
          command: print-pipeline-id
  save-helo-world-output:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "print Hello"
          command: echo "Hello, world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt

  print-world:
    docker:
     - image: cimg/base:stable
    steps:
      - run:
          name: "print world"
          command: "echo world!"
  print-output-file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "print my env name"
          command: |
            cat ~/output.txt
      

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  save-hello-world-output:
    jobs:
      - print-workflow-id
      - save-helo-world-output
      - print-output-file:
          requires:
            -  save-helo-world-output